protected/models/OrderForm.php
<?php

class OrderForm extends CFormModel
{
	public $product;
	public $unit;
	public $name;
	public $phone;
	public $email;
	public $quantity;
	public $deliveryDate;
	public $notes;
	public $image;

	public function rules()
	{
		return array(
			array('product, unit, name, phone, email, quantity', 'required'),
			array('email', 'email'),
			array('image', 'file', 'types' => 'jpg, jpeg, gif, png', 'allowEmpty' => true),
			array('deliveryDate, notes', 'safe'),
		);
	}

	public function attributeLabels()
	{
		return array(
			'unit' => 'Onde deseja retirar seu pedido?',
			'name' => 'Nome',
			'phone' => 'Telefone',
			'email' => 'E-mail',
			'quantity' => 'Quantidade / Peso',
			'deliveryDate' => 'Data / Hora Retirada',
			'image' => 'Imagem',
			'notes' => 'Observações',
		);
	}

	public function getUnitOptions()
	{
		return CHtml::listData(Unit::model()->findAll(array('order' => 'city, name')), 'id', 'name', 'city');
	}

	public function process()
	{
		$unit = Unit::model()->findByPk($this->unit);

		$message = new YiiMailMessage;
		$message->setTo($unit->email);
		$message->setFrom(Yii::app()->params['mail.senderEmail']);
		$message->setReplyTo($this->email);
		$body = Yii::app()->controller->renderPartial(
			'application.views.mail.internal.order', 
			array('orderForm' => $this, 'message' => $message), true
		);	
		$message->setBody(array('message' => $message, 'content' => $body), 'text/html');
		
		if ($this->image && $this->image instanceof CUploadedFile) {
			$path = APP_FILE_PATH . DIRECTORY_SEPARATOR . 'imagem.' . $this->image->extensionName;
			$this->image->saveAs($path);
			$message->attach(Swift_Attachment::fromPath($path));	
		}

		$send = Yii::app()->mail->send($message);
		return $send;
	}
}

protected/controllers/ProductController.php
<?php

class ProductController extends Controller
{
	public function actionIndex($category = null, $id = null) 
	{
		$categories = Category::model()
			->of('products')
			->isChild()
			->findAll(array(
				'index' => 'id',
				'order' => 't.name',
			));

		if ($category === null) {
			$currentCategory = reset($categories);
			$this->redirect(array('product/index', 'category' => $currentCategory->alias));
		} else {
			foreach ($categories as $item) {
				if ($item->alias == $category) {
					$currentCategory = $item;
					break;
				}
			}

			if (empty($currentCategory)) {
				$currentCategory = Category::model()->findByAttributes(array('alias' => $category));
				$products = Product::model()->with('categories.parent')->findAll(array(
					'condition' => 'parent.id = :category',
					'params' => array(':category' => $currentCategory->id),
				));

				if ($currentCategory === null)
					throw new CHttpException(404, 'Página não encontrada.');
			}
		}

		if (empty($products))
			$products = $currentCategory->products(array('order' => 'name'));

		$this->render('index', array(
			'currentCategory' => $currentCategory,
			'categories' => $categories, 
			'products' => $products, 
		));
	}

	public function actionOrder($id)
	{
		$product = Product::model()->findByPk($id);

		if ($product === null)
			throw new CHttpException(404, 'Página não encontrada.');

		$orderForm = new OrderForm;
		$orderForm->product = $product;
		
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'orderForm') {
			echo CActiveForm::validate($orderForm);
			Yii::app()->end();
		}
		
		if (isset($_POST['OrderForm'])) {
			$orderForm->attributes = $_POST['OrderForm'];
			$orderForm->image = CUploadedFile::getInstance($orderForm, 'image');

			if ($orderForm->validate()) {
				if ($orderForm->process())
					Yii::app()->user->setAlert(WebUser::ALERT_SUCCESS, 'Seu pedido foi enviado com sucesso.');					
				else
					Yii::app()->user->setAlert(WebUser::ALERT_DANGER, 'Não foi possível enviar o pedido. Por favor, tente novamente mais tarde.');

				$this->redirect(Yii::app()->homeUrl);
			} else
				Yii::app()->user->setAlert(WebUser::ALERT_DANGER, current(current($orderForm->getErrors())));
		}

		$this->render('order', array('orderForm' => $orderForm, 'product' => $product));
	}
}

protected/views/product/_orderForm.php
<?php $model = isset($model) ? $model : new OrderForm; ?>

<?php $form = $this->beginWidget('CActiveForm', array(
	'id' => 'orderForm',
	'method' => 'post',
	'action' => array('/product/order', 'id' => $product->id),
	'enableAjaxValidation' => true,
	'enableClientValidation' => true,
	'clientOptions' => array(
		'validateOnSubmit' => true,
		'errorCssClass' => 'has-error',
		'successCssClass' => 'has-success',
	),
	'htmlOptions' => array(
		'enctype' => 'multipart/form-data',
	),
)); ?>


<div class="row">
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('name') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'name'); ?>
			<?php echo $form->textField($model, 'name', array('class' => 'form-control')); ?>
			<?php echo $form->error($model, 'name', array('class' => 'help-block')); ?>
		</div>			
	</div>
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('unit') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'unit'); ?>
			<?php echo $form->dropDownList($model, 'unit', $model->unitOptions, array('class' => 'form-control', 'empty' => '')); ?>
			<?php echo $form->error($model, 'unit', array('class' => 'help-block')); ?>
		</div>				
	</div>
</div>

<div class="row">
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('phone') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'phone'); ?>
			<?php echo $form->textField($model, 'phone', array('class' => 'form-control')); ?>
			<?php echo $form->error($model, 'phone', array('class' => 'help-block')); ?>
		</div>				
	</div>
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('email') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'email'); ?>
			<?php echo $form->textField($model, 'email', array('class' => 'form-control')); ?>
			<?php echo $form->error($model, 'email', array('class' => 'help-block')); ?>
		</div>					
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('quantity') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'quantity'); ?>
			<?php echo $form->textField($model, 'quantity', array('class' => 'form-control')); ?>
			<?php echo $form->error($model, 'quantity', array('class' => 'help-block')); ?>
		</div>					
	</div>
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('deliveryDate') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'deliveryDate'); ?>
			<?php echo $form->textField($model, 'deliveryDate', array('class' => 'form-control')); ?>
			<?php echo $form->error($model, 'deliveryDate', array('class' => 'help-block')); ?>
		</div>				
	</div>
</div>
<div class="form-group<?php echo $model->hasErrors('notes') ? ' has-error' : ''; ?>">
	<?php echo $form->labelEx($model, 'notes'); ?>
	<?php echo $form->textArea($model, 'notes', array('class' => 'form-control')); ?>
	<?php echo $form->error($model, 'notes', array('class' => 'help-block')); ?>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group<?php echo $model->hasErrors('image') ? ' has-error' : ''; ?>">
			<?php echo $form->labelEx($model, 'image'); ?>
			<?php echo $form->fileField($model, 'image', array('class' => 'form-control')); ?>
			<?php echo $form->error($model, 'image', array('class' => 'help-block')); ?>
		</div>
	</div>
	<div class="col-sm-6">
		<div class="form-group">
			<label class="control-label">&nbsp;</label>
			<button type="submit" class="btn btn-primary btn-block btn-sm"><i class="fa fa-ok"></i> Enviar Pedido</button>
		</div>					
	</div>
</div>

<?php $this->endWidget(); ?>

protected/views/product/index.php
<?php 
$this->pageTitle = 'Bolos';
$this->pageSubtitle = 'Navegue entre as saborosas opções de bolos, faça sua escolha e nos envie seu pedido.'; 
$this->banners = array(2);

$categoriesParents = array();
$categoriesByParent = array();
$categoriesWithProducts = array();

foreach ($categories as $category) {
	$categoriesParents[$category->parent_id] = $category->parent;
	$categoriesByParent[$category->parent_id][$category->id] = $category;

	if ($category->products)
		$categoriesWithProducts[] = $category;
}
?>

<div id="produtos" class="row">
	<div class="col-md-2">
		<nav class="product-category-sidenav" role="complementary">	
			<a class="dropdown-toggle" data-toggle="dropdown">
				<?php echo (null !== $currentCategory) ? CHtml::encode($currentCategory->name) : 'Categoria'; ?> 
				<span class="caret"></span>	
			</a>
			<ul class="dropdown-menu" role="menu">
				<?php foreach ($categoriesByParent as $parentId => $categories) : ?>

				<li class="dropdown-header"><?php echo CHtml::encode($categoriesParents[$parentId]->name); ?></li>

				<?php foreach ($categories as $category) : ?>

				<li<?php echo $category->id == $currentCategory->id ? ' class="active"' : ''; ?>>
					<a href="<?php echo $this->createUrl('index', array('category' => $category->alias)); ?>">
						<?php echo CHtml::encode($category->name); ?>
					</a>
				</li>

				<?php endforeach; ?>

				<?php endforeach; ?>
			</ul>
		
			<ul class="nav">
				<?php foreach ($categoriesByParent as $parentId => $categories) : ?>

				<li>
					<ul class="nav">
						<li><h4><?php echo CHtml::encode($categoriesParents[$parentId]->name); ?></h4></li>

						<?php foreach ($categories as $category) : ?>

						<li<?php echo $category->id == $currentCategory->id ? ' class="active"' : ''; ?>>
							<a href="<?php echo $this->createUrl('index', array('category' => $category->alias)); ?>#produtos">
								<?php echo CHtml::encode($category->name); ?>
							</a>
						</li>

						<?php endforeach; ?>
					</ul>						
				</li>

				<?php endforeach; ?>
			</ul>
		</nav>
	</div>
	<div class="col-md-8">
		<?php if ($products) : ?>

		<?php $this->renderPartial('_orderForm', array('product' => $products[0]), true); ?>

		<div class="product-group">
			<div id="productGroupCarousel" class="carousel slide" data-ride="carousel">
				<div class="carousel-inner">

					<?php foreach ($products as $i => $product) : ?>
				
					<div class="product item<?php echo $i === 0 ? ' active' : ''; ?>" data-view-url="<?php echo $this->createUrl('order', array('id' => $product->id, 'modal' => true)); ?>">
						<div class="block-fluid-group">
							<img class="product-img block-fluid block-fluid-middle-center" src="<?php echo $product->image ? $product->image->url : null; ?>" alt="<?php echo CHtml::encode($product->name); ?>">
						</div>
						<div class="carousel-caption">
							<h2 class="product-name"><?php echo CHtml::encode($product->name); ?></h2>
							<p class="product-description"><?php echo CHtml::encode($product->description); ?></p>								

							<?php if ($product->sweetness > 0) : ?>

							<p class="product-sweetness">
								<img class="product-sweetness-img" src="<?php echo APP_IMG_URL; ?>/product-sweetness-<?php echo CHtml::encode($product->sweetness); ?>.png">
								<span class="product-sweetness-label">Medidor de Doçura</span>
							</p>

							<?php endif; ?>								
						</div>
					</div>

					<?php endforeach; ?>
				</div>

				<?php if (count($products) > 1) : ?>

				<a class="left carousel-control" href="#productGroupCarousel" data-slide="prev"><span class="icon-prev"></span></a>
				<a class="right carousel-control" href="#productGroupCarousel" data-slide="next"><span class="icon-next"></span></a>
			
				<?php endif; ?>
			</div>
			<button class="btn btn-primary btn-lg product-order-btn">
				<span class="h4"><i class="fa fa-edit"></i> FAZER PEDIDO</span>
			</button>			
		</div>

		<?php else : ?>

		<div class="panel">
			<div class="panel-body">
				<?php 
				$categoriesLabel = '';
				foreach ($categoriesWithProducts as $category) {
					$categoriesLabel .= CHtml::link($category->name, $this->createUrl('index', array('category' => $category->alias)), array('class' => 'label label-primary'));
					$categoriesLabel .= ' ';
				}
				?>

				<h2>Em construção</h2>
				<p>Desculpe, mas não há produtos cadastros nesta categoria no momento. Por favor, retorne em breve.<br>
				Enquanto isso, que tal consultar alguma das categorias abaixo?</p>
				<p><?php echo $categoriesLabel; ?></p>
			</div>
		</div>

		<?php endif; ?>
	</div>

	<div class="col-md-2">
		<div class="product-thumbnail-group">
			<div id="productThumbnailGroupCarousel" class="carousel carousel-vertical slide" data-ride="carousel">
				<div class="carousel-inner">
					<?php $productsGroup = array_chunk($products, 4); ?>

					<?php foreach ($productsGroup as $i => $products) : ?>

					<div class="item<?php echo $i === 0 ? ' active' : ''; ?>">

					<?php foreach ($products as $ii => $product) : ?>					
					
					<div class="product-thumbnail" data-target="#productGroupCarousel" data-slide-to="<?php echo ($i * 4) + $ii; ?>">
						<div class="block-fluid-group">
							<img class="product-thumbnail-img block-fluid block-fluid-middle-center" alt="<?php echo CHtml::encode($product->name); ?>" src="<?php echo $product->image ? $product->image->url : null; ?>">								
						</div>
						<h5 class="product-thumbnail-title"><?php echo CHtml::encode($product->name); ?></h5>
					</div>

					<?php endforeach; ?>

					</div>

					<?php endforeach; ?>
				</div>
				<a class="left carousel-control" href="#productThumbnailGroupCarousel" data-slide="prev"><span class="fa fa-chevron-up"></span></a>
				<a class="right carousel-control" href="#productThumbnailGroupCarousel" data-slide="next"><span class="fa fa-chevron-down"></span></a>
			</div>
		</div>
	</div>
</div>

<?php 
$js = <<<JS
$('.product-order-btn').on('click', function (e) {
	e.preventDefault();
	var url = $(this).parents('.product-group').find('[data-view-url].active').attr('data-view-url');

	$('#modal').modal({ 'remote': url });
});
JS;
Yii::app()->clientScript->registerPackage('owl.carousel'); 
Yii::app()->clientScript->registerPackage('prettyPhoto'); 
Yii::app()->clientScript->registerScript('post.index', $js, CClientScript::POS_END); 
?>

protected/views/product/order.php
<?php 
if (Yii::app()->request->getParam('modal'))
	$this->layout = 'modal';

$this->icon = 'edit';
$this->width = 8;
$this->pageTitle = 'Pedido'; 
$this->pageSubtitle = 'Preencha os itens abaixo e em breve entraremos em contato.';
$this->banners = array(2);
?>

<div class="product-order">
	<div class="product">
		<div class="row">
			<div class="col-xs-6">
				<p><img class="img-responsive" src="<?php echo $product->image ? $product->image->url : null; ?>" alt="<?php echo CHtml::encode($product->name); ?>"></p>
			</div>
			<div class="col-xs-6">
				<h3><?php echo CHtml::encode($product->name); ?></h3>
				<p><?php echo CHtml::encode($product->description); ?></p>				
			</div>
		</div>
	</div>

	<?php $this->renderPartial('_orderForm', array('product' => $product, 'model' => $orderForm)); ?>
</div>